        const puzzles = [
            /* 1-5 Tutorial */
            // one ball with cascade
            { target: 18, board: [[], [{v:3, c:COLORS.RED}], [{v:2, c:COLORS.RED}, {v:6, c:COLORS.BLUE}, {v:3, c:COLORS.RED}], [], []], queue: [{v:3, c:COLORS.BLUE}] },
            // color match
            { target: 20, board: [[{v:2, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}, {v:5, c:COLORS.BLUE}], [], [{v:1, c:COLORS.RED}], [{v:2, c:COLORS.RED}]], queue: [{v:5, c:COLORS.RED}, {v:2, c:COLORS.BLUE}] },
            // numbers twice
            { target: 24, board: [[{v:2, c:COLORS.RED}], [{v:6, c:COLORS.RED}, {v:2, c:COLORS.BLUE},{v:4, c:COLORS.BLUE}], [], [{v:4, c:COLORS.RED}, {v:8, c:COLORS.BLUE}], [{v:3, c:COLORS.RED},]], queue: [{v:2, c:COLORS.RED}, {v:3, c:COLORS.BLUE}] },
            // Using 1 as connect
            { target: 20, board: [[{v:5, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}], [{v:5, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}], [{v:5, c:COLORS.RED}]], queue: [{v:1, c:COLORS.BLUE}, {v:1, c:COLORS.RED}] },
            // three balls plan ahead
            { target: 12, board: [[{v:2, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [], [{v:2, c:COLORS.RED}, {v:3, c:COLORS.RED}], []], queue: [{v:6, c:COLORS.BLUE}, {v:1, c:COLORS.RED}, {v:6, c:COLORS.BLUE}] },
            
            // main set
            { target: 12, board: [[{v:3, c:COLORS.RED}, {v:2, c:COLORS.RED}], [], [{v:2, c:COLORS.RED}], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.RED}, {v:2, c:COLORS.RED}], []], queue: [{v:3, c:COLORS.RED}, {v:1, c:COLORS.RED}] },
            { target: 45, board: [[], [{v:3, c:COLORS.RED}], [{v:3, c:COLORS.RED}], [{v:5, c:COLORS.BLUE}, {v:5, c:COLORS.RED}], [{v:3, c:COLORS.BLUE}, {v:15, c:COLORS.RED}]], queue: [{v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}] },
            { target: 44, board: [[], [{v:2, c:COLORS.BLUE}], [{v:22, c:COLORS.RED}], [{v:11, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}, {v:11, c:COLORS.RED}]], queue: [{v:2, c:COLORS.RED}, {v:1, c:COLORS.BLUE}] },
            { target: 50, board: [[{v:5, c:COLORS.RED}], [{v:5, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:5, c:COLORS.RED}, {v:5, c:COLORS.RED}], [], [{v:5, c:COLORS.BLUE}]], queue: [{v:5, c:COLORS.BLUE}, {v:2, c:COLORS.RED}] },
            { target: 30, board: [[], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [{v:6, c:COLORS.BLUE}, {v:5, c:COLORS.RED}, {v:15, c:COLORS.BLUE}], [{v:10, c:COLORS.RED}], []], queue: [{v:3, c:COLORS.RED}, {v:5, c:COLORS.BLUE}] },
            { target: 28, board: [[{v:2, c:COLORS.BLUE}], [{v:7, c:COLORS.RED}, {v:7, c:COLORS.BLUE}, {v:14, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:1, c:COLORS.BLUE}], [], [{v:14, c:COLORS.BLUE}]], queue: [{v:2, c:COLORS.BLUE}, {v:4, c:COLORS.RED}] },
            { target: 12, board: [[], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [{v:6, c:COLORS.RED}, {v:3, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], []], queue: [{v:4, c:COLORS.RED}, {v:6, c:COLORS.BLUE}] }, // hard but good
            { target: 54, board: [[], [{v:3, c:COLORS.RED}], [{v:1, c:COLORS.RED}], [{v:3, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:3, c:COLORS.RED}, {v:27, c:COLORS.BLUE}]], queue: [{v:9, c:COLORS.RED}, {v:1, c:COLORS.RED}] },
            { target: 88, board: [[{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:22, c:COLORS.RED}], [{v:1, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}, {v:4, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}], []], queue: [{v:44, c:COLORS.RED}, {v:22, c:COLORS.BLUE}] },
            { target: 24, board: [[{v:6, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}], [{v:4, c:COLORS.BLUE}], []], queue: [{v:8, c:COLORS.RED}, {v:2, c:COLORS.BLUE}] },
            { target: 30, board: [[{v:3, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}, {v:6, c:COLORS.RED}, {v:3, c:COLORS.BLUE}, {v:5, c:COLORS.BLUE}], [{v:3, c:COLORS.RED}], [], []], queue: [{v:10, c:COLORS.RED}, {v:5, c:COLORS.RED}] },
            { target: 90, board: [[{v:2, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:5, c:COLORS.BLUE}, {v:5, c:COLORS.BLUE}], [], [{v:1, c:COLORS.BLUE}], [{v:9, c:COLORS.BLUE}]], queue: [{v:5, c:COLORS.BLUE}, {v:9, c:COLORS.BLUE}] },
            { target: 84, board: [[], [{v:7, c:COLORS.BLUE}, {v:6, c:COLORS.BLUE}], [{v:4, c:COLORS.BLUE}, {v:7, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}], [{v:7, c:COLORS.BLUE}]], queue: [{v:1, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}] },
            { target: 60, board: [[{v:6, c:COLORS.BLUE}], [], [{v:2, c:COLORS.BLUE}], [{v:6, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}, {v:5, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}]], queue: [{v:5, c:COLORS.BLUE}, {v:4, c:COLORS.BLUE}] },
            { target: 42, board: [[], [{v:3, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:14, c:COLORS.RED}], [{v:1, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}]], queue: [{v:7, c:COLORS.BLUE}, {v:21, c:COLORS.RED}] },
            { target: 20, board: [[{v:2, c:COLORS.BLUE}, {v:5, c:COLORS.RED}, {v:2, c:COLORS.RED}], [{v:5, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}, {v:10, c:COLORS.BLUE}], [], []], queue: [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}] },
            { target: 44, board: [[{v:4, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}, {v:22, c:COLORS.RED}], [{v:11, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:22, c:COLORS.RED}], [{v:2, c:COLORS.RED}], []], queue: [{v:11, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:1, c:COLORS.RED}] },
            { target: 18, board: [[{v:3, c:COLORS.RED}, {v:3, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}], [], [{v:3, c:COLORS.BLUE}, {v:9, c:COLORS.RED}], [{v:2, c:COLORS.RED}]], queue: [{v:2, c:COLORS.RED}, {v:3, c:COLORS.BLUE}, {v:6, c:COLORS.BLUE}] },
            { target: 63, board: [[{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}], [], [{v:3, c:COLORS.BLUE}, {v:7, c:COLORS.RED}, {v:3, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}]], queue: [{v:7, c:COLORS.BLUE}, {v:7, c:COLORS.BLUE}, {v:9, c:COLORS.RED}] },
            { target: 100, board: [[], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}], [{v:5, c:COLORS.BLUE}, {v:1, c:COLORS.RED}, {v:1, c:COLORS.RED}], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], []], queue: [{v:25, c:COLORS.RED}, {v:25, c:COLORS.BLUE}, {v:10, c:COLORS.BLUE}] }, 
            { target: 12, board: [[], [{v:2, c:COLORS.BLUE}], [{v:1, c:COLORS.BLUE}, {v:4, c:COLORS.RED}], [{v:3, c:COLORS.RED}, {v:1, c:COLORS.BLUE}, {v:4, c:COLORS.RED}], [{v:3, c:COLORS.RED}, {v:2, c:COLORS.BLUE}]], queue: [{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:4, c:COLORS.RED}] }, 
            { target: 88, board: [[{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:22, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:11, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [{v:22, c:COLORS.RED}], []], queue: [{v:11, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:4, c:COLORS.BLUE}] }, 
            { target: 56, board: [[], [], [{v:7, c:COLORS.BLUE}, {v:1, c:COLORS.BLUE}, {v:7, c:COLORS.BLUE}, {v:1, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:14, c:COLORS.RED}, {v:7, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}, {v:1, c:COLORS.BLUE}, {v:7, c:COLORS.BLUE}], []], queue: [{v:4, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:8, c:COLORS.BLUE}] },
            { target: 100, board: [[{v:5, c:COLORS.RED}, {v:10, c:COLORS.BLUE}, {v:20, c:COLORS.RED}], [], [{v:2, c:COLORS.BLUE}, {v:20, c:COLORS.RED}], [{v:10, c:COLORS.BLUE}], [{v:1, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}]], queue: [{v:5, c:COLORS.RED}, {v:10, c:COLORS.BLUE}, {v:5, c:COLORS.BLUE}] }, 
            { target: 44, board: [[], [], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [{v:1, c:COLORS.RED}, {v:1, c:COLORS.BLUE}, {v:22, c:COLORS.BLUE}, {v:4, c:COLORS.BLUE}, {v:11, c:COLORS.RED}], [{v:11, c:COLORS.RED}]], queue: [{v:11, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:4, c:COLORS.RED}] }, 
            { target: 18, board: [[{v:3, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}, {v:2, c:COLORS.RED},], [{v:3, c:COLORS.RED}, {v:6, c:COLORS.BLUE},], [{v:9, c:COLORS.BLUE}], []], queue: [{v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}] }, 
            { target: 24, board: [[{v:2, c:COLORS.RED}], [{v:1, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:4, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [{v:4, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}], []], queue: [{v:6, c:COLORS.BLUE}, {v:6, c:COLORS.RED}, {v:6, c:COLORS.BLUE}] }, 
            { target: 36, board: [[{v:3, c:COLORS.RED}, {v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.RED}], [{v:2, c:COLORS.RED}, {v:1, c:COLORS.RED}, {v:4, c:COLORS.BLUE}], [], []], queue: [{v:3, c:COLORS.RED}, {v:4, c:COLORS.RED}, {v:2, c:COLORS.RED}] },
            { target: 100, board: [[{v:5, c:COLORS.BLUE}], [], [{v:5, c:COLORS.RED}, {v:4, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:5, c:COLORS.BLUE}, {v:1, c:COLORS.RED}], [{v:10, c:COLORS.BLUE}]], queue: [{v:2, c:COLORS.BLUE}, {v:10, c:COLORS.RED}, {v:25, c:COLORS.BLUE}] },
            { target: 36, board: [[], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:1, c:COLORS.RED}], [{v:3, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:1, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}], []], queue: [{v:9, c:COLORS.RED}, {v:9, c:COLORS.BLUE}, {v:6, c:COLORS.BLUE}] }, 
            { target: 99, board: [[{v:11, c:COLORS.BLUE}, {v:11, c:COLORS.BLUE}], [], [{v:3, c:COLORS.BLUE}], [{v:11, c:COLORS.RED}, {v:11, c:COLORS.BLUE}], [{v:9, c:COLORS.BLUE}]], queue: [{v:1, c:COLORS.BLUE}, {v:9, c:COLORS.RED}, {v:3, c:COLORS.BLUE}] },
            { target: 88, board: [[{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}, {v:1, c:COLORS.RED}, {v:11, c:COLORS.BLUE}], [{v:4, c:COLORS.BLUE}, {v:11, c:COLORS.RED}], [{v:11, c:COLORS.RED}], []], queue: [{v:4, c:COLORS.BLUE}, {v:4, c:COLORS.RED}, {v:2, c:COLORS.RED}] }, 
            { target: 54, board: [[{v:3, c:COLORS.BLUE}], [{v:1, c:COLORS.BLUE}, {v:3, c:COLORS.RED}], [{v:9, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}], [{v:9, c:COLORS.RED}, {v:3, c:COLORS.RED}], []], queue: [{v:6, c:COLORS.RED}, {v:6, c:COLORS.BLUE}, {v:6, c:COLORS.RED}] }, 
            { target: 12, board: [[], [], [{v:2, c:COLORS.RED}, {v:1, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:6, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:2, c:COLORS.RED}], []], queue: [{v:6, c:COLORS.RED}, {v:1, c:COLORS.BLUE}, {v:3, c:COLORS.RED}] }, 
            { target: 18, board: [[{v:3, c:COLORS.RED}], [{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}], [{v:1, c:COLORS.RED}], [{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}], [{v:1, c:COLORS.RED}, {v:3, c:COLORS.BLUE}]], queue: [{v:6, c:COLORS.RED}, {v:3, c:COLORS.RED}, {v:2, c:COLORS.BLUE}] }, 
            { target: 54, board: [[], [{v:6, c:COLORS.RED}], [{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:3, c:COLORS.RED}], [{v:6, c:COLORS.RED}], [{v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}]], queue: [{v:2, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:9, c:COLORS.BLUE}] }, 
            { target: 28, board: [[{v:7, c:COLORS.BLUE}], [{v:1, c:COLORS.BLUE}, {v:1, c:COLORS.RED}, {v:14, c:COLORS.RED}, {v:4, c:COLORS.RED}, {v:7, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [], []], queue: [{v:7, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:4, c:COLORS.BLUE}] }, 
            { target: 18, board: [[{v:3, c:COLORS.RED}], [{v:3, c:COLORS.BLUE}, {v:6, c:COLORS.RED}, {v:6, c:COLORS.BLUE}], [], [{v:2, c:COLORS.RED}, {v:1, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}]], queue: [{v:9, c:COLORS.RED}, {v:6, c:COLORS.BLUE}, {v:1, c:COLORS.RED}] }, // easy
            { target: 99, board: [[], [{v:3, c:COLORS.RED}], [{v:1, c:COLORS.RED}, {v:9, c:COLORS.BLUE}], [{v:11, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:9, c:COLORS.BLUE}], [{v:11, c:COLORS.BLUE},]], queue: [{v:11, c:COLORS.RED}, {v:11, c:COLORS.BLUE}, {v:9, c:COLORS.BLUE}] }, 
            { target: 24, board: [[{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [], [{v:2, c:COLORS.RED}], [{v:3, c:COLORS.RED}, {v:3, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:4, c:COLORS.RED}], [{v:3, c:COLORS.RED}]], queue: [{v:1, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:4, c:COLORS.BLUE}] }, //easy
            { target: 88, board: [[], [{v:11, c:COLORS.RED}, {v:4, c:COLORS.RED}], [{v:1, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [], [{v:2, c:COLORS.RED}]], queue: [{v:22, c:COLORS.RED}, {v:4, c:COLORS.RED}, {v:44, c:COLORS.BLUE}] }, 
            { target: 36, board: [[{v:1, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}], [{v:6, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:12, c:COLORS.RED}], [], [{v:3, c:COLORS.RED}, {v:6, c:COLORS.BLUE}, {v:12, c:COLORS.RED}]], queue: [{v:3, c:COLORS.RED}, {v:6, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}] },
            { target: 70, board: [[], [{v:10, c:COLORS.RED}, {v:5, c:COLORS.RED}], [{v:5, c:COLORS.BLUE}, {v:7, c:COLORS.BLUE}, {v:1, c:COLORS.RED}], [{v:5, c:COLORS.BLUE}], [{v:10, c:COLORS.RED}]], queue: [{v:14, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:7, c:COLORS.RED}] },
            { target: 18, board: [[{v:9, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}], [], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}]], queue: [{v:1, c:COLORS.BLUE}, {v:9, c:COLORS.RED}, {v:3, c:COLORS.BLUE}] },
            { target: 66, board: [[{v:6, c:COLORS.BLUE}], [{v:3, c:COLORS.RED}], [{v:3, c:COLORS.RED}, {v:11, c:COLORS.RED}, {v:1, c:COLORS.BLUE}], [{v:6, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}], []], queue: [{v:22, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:11, c:COLORS.BLUE}] },
            { target: 84, board: [[], [{v:21, c:COLORS.BLUE}, {v:7, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}, {v:4, c:COLORS.RED}, {v:4, c:COLORS.BLUE}], [], [{v:2, c:COLORS.BLUE}, {v:6, c:COLORS.BLUE}]], queue: [{v:21, c:COLORS.RED}, {v:7, c:COLORS.BLUE}, {v:4, c:COLORS.BLUE}] },
            { target: 36, board: [[], [{v:6, c:COLORS.BLUE}, {v:12, c:COLORS.BLUE}, {v:6, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}, {v:4, c:COLORS.BLUE}, {v:6, c:COLORS.RED}], [], [{v:3, c:COLORS.RED}]], queue: [{v:2, c:COLORS.RED}, {v:4, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}] },
            { target: 12, board: [[], [], [{v:2, c:COLORS.RED}, {v:1, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:6, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:2, c:COLORS.RED}], []], queue: [{v:6, c:COLORS.RED}, {v:1, c:COLORS.BLUE}, {v:3, c:COLORS.RED}] }, 
            { target: 40, board: [[], [{v:4, c:COLORS.RED}, {v:2, c:COLORS.RED}], [{v:4, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}], [{v:1, c:COLORS.BLUE}, {v:2, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}]], queue: [{v:10, c:COLORS.RED}, {v:10, c:COLORS.BLUE}, {v:10, c:COLORS.RED}] }, 
            { target: 50, board: [[{v:5, c:COLORS.RED}], [{v:5, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:1, c:COLORS.BLUE}], [{v:5, c:COLORS.BLUE}, {v:10, c:COLORS.RED}, {v:1, c:COLORS.RED}], [{v:25, c:COLORS.RED}], []], queue: [{v:5, c:COLORS.BLUE}, {v:5, c:COLORS.RED}, {v:2, c:COLORS.RED}] }, 
            { target: 60, board: [[], [{v:15, c:COLORS.RED}, {v:5, c:COLORS.RED}], [{v:3, c:COLORS.RED}, {v:4, c:COLORS.BLUE}, {v:4, c:COLORS.RED}], [], [{v:2, c:COLORS.RED}, {v:6, c:COLORS.RED}]], queue: [{v:15, c:COLORS.BLUE}, {v:5, c:COLORS.RED}, {v:4, c:COLORS.RED}] }, 
            { target: 28, board: [[], [], [{v:2, c:COLORS.BLUE}, {v:1, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:14, c:COLORS.RED}], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}], []], queue: [{v:14, c:COLORS.BLUE}, {v:1, c:COLORS.RED}, {v:7, c:COLORS.BLUE}] }, 
            { target: 30, board: [[], [{v:6, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}], [{v:3, c:COLORS.RED}, {v:5, c:COLORS.RED}, {v:1, c:COLORS.BLUE}], [{v:3, c:COLORS.RED}], [{v:6, c:COLORS.BLUE}]], queue: [{v:10, c:COLORS.BLUE}, {v:2, c:COLORS.RED}, {v:5, c:COLORS.BLUE}] }, 
            { target: 72, board: [[], [{v:3, c:COLORS.RED}, {v:6, c:COLORS.BLUE}], [{v:3, c:COLORS.BLUE}, {v:2, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}], [{v:2, c:COLORS.RED}, {v:2, c:COLORS.RED}]], queue: [{v:12, c:COLORS.RED}, {v:3, c:COLORS.RED}, {v:2, c:COLORS.BLUE}] }, 
            { target: 75, board: [[{v:3, c:COLORS.RED}, {v:3, c:COLORS.RED}], [], [{v:5, c:COLORS.RED}], [{v:3, c:COLORS.BLUE}, {v:3, c:COLORS.RED}], [{v:25, c:COLORS.RED}]], queue: [{v:1, c:COLORS.RED}, {v:25, c:COLORS.BLUE}, {v:5, c:COLORS.RED}] }, 
            { target: 12, board: [[], [{v:4, c:COLORS.BLUE}], [{v:2, c:COLORS.RED}, {v:6, c:COLORS.BLUE}, {v:1, c:COLORS.BLUE}], [{v:2, c:COLORS.BLUE}, {v:3, c:COLORS.RED}, {v:1, c:COLORS.RED}], [{v:2, c:COLORS.BLUE}]], queue: [{v:2, c:COLORS.RED}, {v:2, c:COLORS.BLUE}, {v:3, c:COLORS.BLUE}] }, // checked to here

        ]